import Head from 'next/head'
import Nav from '../components/nav'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
const inter = Inter({ subsets: ['latin'] })
export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Home</h1>

    </>
  )
}

Home.getLayout = function pageLayout(page) {
  return (
    <>
      <Nav/>
      {page}
      <footer className="text-center bg-gray-800 text-white py-4 fixed bottom-0 w-full">
        <p>&copy; 2022 Footer</p>
      </footer>

    </>
  )
}
